name = "Console-idated"
author = "S_N00B"
version = "1.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee702ed41c9844393fa87c99541dcc55f52089bf5ee5129b64997924e5489505"

[versions]
fabric = "0.16.10"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.1", "1.20.4"]
